# Generated by Django 4.0.4 on 2022-05-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niftybanknifty',
            old_name='banknifty_LV',
            new_name='bank_nifty_future',
        ),
        migrations.RenameField(
            model_name='niftybanknifty',
            old_name='banknifty_MTM',
            new_name='bank_nifty_spot',
        ),
        migrations.RenameField(
            model_name='niftybanknifty',
            old_name='banknifty_PV',
            new_name='iv',
        ),
        migrations.RenameField(
            model_name='niftybanknifty',
            old_name='banknifty_future',
            new_name='loss',
        ),
        migrations.RenameField(
            model_name='niftybanknifty',
            old_name='banknifty_loss',
            new_name='mtm',
        ),
        migrations.RenameField(
            model_name='niftybanknifty',
            old_name='banknifty_profit',
            new_name='profit',
        ),
        migrations.RenameField(
            model_name='niftybanknifty',
            old_name='banknifty_spot',
            new_name='pv',
        ),
        migrations.RemoveField(
            model_name='niftybanknifty',
            name='nifty_LV',
        ),
        migrations.RemoveField(
            model_name='niftybanknifty',
            name='nifty_MTM',
        ),
        migrations.RemoveField(
            model_name='niftybanknifty',
            name='nifty_PV',
        ),
        migrations.RemoveField(
            model_name='niftybanknifty',
            name='nifty_loss',
        ),
        migrations.RemoveField(
            model_name='niftybanknifty',
            name='nifty_profit',
        ),
    ]
