# Generated by Django 4.0.4 on 2022-05-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_client', '0002_rename_banknifty_lv_niftybanknifty_bank_nifty_future_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niftybanknifty',
            old_name='iv',
            new_name='lt',
        ),
        migrations.RenameField(
            model_name='niftybanknifty',
            old_name='pv',
            new_name='vt',
        ),
    ]
