# Generated by Django 4.0.4 on 2022-05-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_client', '0003_rename_iv_niftybanknifty_lt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradestrategies',
            name='strategies',
            field=models.CharField(max_length=10),
        ),
    ]
