# Generated by Django 4.0.4 on 2022-05-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_client', '0005_alter_tradestrategies_strategies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niftybanknifty',
            name='bank_nifty_future',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='niftybanknifty',
            name='bank_nifty_spot',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='niftybanknifty',
            name='loss',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='niftybanknifty',
            name='lt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='niftybanknifty',
            name='mtm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='niftybanknifty',
            name='nifty_future',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='niftybanknifty',
            name='nifty_spot',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='niftybanknifty',
            name='profit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='niftybanknifty',
            name='vt',
            field=models.FloatField(null=True),
        ),
    ]
