# Generated by Django 4.0.4 on 2022-04-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AHC_CLIENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahc_client_id', models.ImageField(auto_created=True, upload_to='')),
                ('ahc_client_name', models.CharField(max_length=200)),
                ('ahc_client_mobile', models.IntegerField()),
                ('ahc_client_email', models.EmailField(max_length=254)),
                ('ahc_client_password', models.CharField(max_length=100)),
            ],
        ),
    ]
