# Generated by Django 4.0.4 on 2022-04-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AHC_CLIENT',
            new_name='Signup_Ahc_Client',
        ),
    ]
