# Generated by Django 4.0.4 on 2022-04-27 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
