# Generated by Django 4.0.4 on 2022-05-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_app', '0002_user_expiry_date_user_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ahc_admin',
            field=models.BooleanField(default=False),
        ),
    ]
