# Generated by Django 4.0.4 on 2022-04-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_app', '0002_rename_ahc_client_signup_ahc_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_ahc_client',
            name='ahc_client_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
