# Generated by Django 4.0.4 on 2022-05-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_app', '0003_user_is_ahc_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_client_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
