# Generated by Django 4.0.4 on 2022-04-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_app', '0003_alter_signup_ahc_client_ahc_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_ahc_client',
            name='ahc_client_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
