# Generated by Django 4.0.4 on 2022-04-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=50)),
                ('broker_id', models.CharField(max_length=50)),
                ('login_id', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=100)),
                ('secret_id', models.CharField(max_length=50)),
            ],
        ),
    ]
