# Generated by Django 4.0.4 on 2022-05-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_broker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Broker',
        ),
    ]
