# Generated by Django 4.0.4 on 2022-05-08 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ahc_broker', '0002_delete_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('secret_id', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
